export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'
export const GAME_FIELD_UPDATE = 'GAME_FIELD_UPDATE'
export const CREATE_ELEMENT = 'CREATE_ELEMENT'

export const SCORE_UPDATE = 'SCORE_UPDATE'
