export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'
export const ROTATE_CLOCKWISE = 'ROTATE_CLOCKWISE'
export const ROTATE_COUNTERCLOCKWISE = 'ROTATE_COUNTERCLOCKWISE'

export const GAME_FIELD_UPDATE = 'GAME_FIELD_UPDATE'
export const GAME_FIELD_CREATE = 'GAME_FIELD_CREATE'
export const CREATE_ELEMENT = 'CREATE_ELEMENT'
export const LOWER_ELEMENT = 'LOWER_ELEMENT'

export const SCORE_UPDATE = 'SCORE_UPDATE'
