export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'
export const MOVE_DOWN = 'MOVE_DOWN'
export const ROTATE_CLOCKWISE = 'ROTATE_CLOCKWISE'
export const ROTATE_COUNTERCLOCKWISE = 'ROTATE_COUNTERCLOCKWISE'

export const GAME_FIELD_UPDATE = 'GAME_FIELD_UPDATE'
export const GAME_FIELD_CREATE = 'GAME_FIELD_CREATE'
export const CREATE_ELEMENT = 'CREATE_ELEMENT'

export const RESTART_GAME = 'RESTART_GAME'

export const SCORE_UPDATE = 'SCORE_UPDATE'

export const SCORES_DONT_SAVE_NEW_SCORE = 'SCORES_DONT_SAVE_NEW_SCORE'
export const SCORES_SAVE_NEW_SCORE = 'SCORES_SAVE_NEW_SCORE'
export const SCORES_GET = 'SCORES_GET'
export const SCORES_POST = 'SCORE_SEND'